"""add_kundali_original_name

Revision ID: 2f81f6eb5f55
Revises: 71ad155155a5
Create Date: 2026-04-06 17:25:09.287661

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2f81f6eb5f55'
down_revision = '71ad155155a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('kundali_original_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'kundali_original_name')
    # ### end Alembic commands ###
